[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
pretty_env_logger = "0.5.0"
tokio = {version = "1.43.0", features = ["full"]}
tokio-stream = "0.1.17"
warp = "0.3.7"

[[bin]]
name = "server"
path = "main.rs"
